# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'day21' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for day21
  # http
  pod 'AFNetworking', '~> 3.2.1'
  # pod 'Kingfisher'
  # ui
  # pod 'RAMAnimatedTabBarController'
  pod 'MJRefresh', '~> 3.1.15'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SnapKit', '~> 4.2.0'
  pod 'TableKit', '~> 2.8.0'
#  pod 'SwiftDate', '~> 4.4.0'
  pod 'FSCalendar', '~> 2.8.0'
  pod 'Toast-Swift', '~> 4.0.0'
  pod 'EmptyDataSet-Swift', '~> 4.2.0'
  pod 'Parchment', '~> 1.4.1'
  pod 'TYCyclePagerView', '~> 1.1.0'
  pod 'PieCharts', '~> 0.0.7'
  pod 'CHIPageControl/Aleppo', '~> 0.1.7'
  pod 'NextGrowingTextView', '~> 1.4.0'
  pod 'Presentr', '~> 1.9.0'
  pod 'Charts', '~> 3.2.0'
  # model
  # pod 'HandyJSON'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SQLite.swift', '~> 0.11.5'
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
  # pod 'FMDB'
  # rx
  pod 'Moya/RxSwift', '~> 11.0.2'
  pod 'NSObject+Rx', '~> 4.4.1'
  pod 'RxGesture', '~> 2.1.0'
  pod 'RxCocoa', '~> 4.4.0'
  pod 'RxKeyboard', '~> 0.9.0'
  # util
  pod 'Then', '~> 2.4.0'
  pod 'Promises', '~> 2.0.1'
  # pod 'ReusableKit'
  pod 'ReSwift', '~> 4.0.1'
  # pod 'ReSwiftRouter'
  pod 'URLNavigator', '~> 2.1.0'
  
  target 'day21Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'day21UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
